# Generated by Django 2.2.5 on 2020-12-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201204_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_comfirmed',
            new_name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
